# Mail.ru Configuration
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=dmitevgen19@mail.ru
spring.mail.password=qwerty1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory